from algorithms.LR_NM.LR_NM_gv import LR_NM_gv
from algorithms.LR_NM.LR_NM_m1 import LR_NM_m1
from algorithms.LR_NM.LR_NM_m2 import LR_NM_m2
from algorithms.LR_NM.LR_NM_m3 import LR_NM_m3
from algorithms.LR_NM.LR_NM_m4 import LR_NM_m4
from algorithms.LR_NM.LR_NM_m5 import LR_NM_m5
from algorithms.LR_NM.LR_NM_m6 import LR_NM_m6
from algorithms.LR_NM.LR_NM_m7 import LR_NM_m7
from algorithms.LR_NM.LR_NM_m8 import LR_NM_m8 
from algorithms.LR_NM.LR_NM_m9 import LR_NM_m9
from algorithms.LR_NM.LR_NM_m10 import LR_NM_m10
from algorithms.LR_NM.LR_NM_m11 import LR_NM_m11
from algorithms.LR_NM.LR_NM_m12 import LR_NM_m12
from algorithms.LR_NM.LR_NM_m13 import LR_NM_m13
from algorithms.LR_NM.LR_NM_m14 import LR_NM_m14
from algorithms.LR_NM.LR_NM_m15 import LR_NM_m15
from algorithms.LR_NM.LR_NM_m16 import LR_NM_m16
from algorithms.LR_NM.LR_NM_m17 import LR_NM_m17
from algorithms.LR_NM.LR_NM_m18 import LR_NM_m18
from algorithms.LR_NM.LR_NM_m19 import LR_NM_m19
from algorithms.LR_NM.LR_NM_m20 import LR_NM_m20
from algorithms.LR_NM.LR_NM_m21 import LR_NM_m21
from algorithms.LR_NM.LR_NM_m22 import LR_NM_m22
from algorithms.LR_NM.LR_NM_m23 import LR_NM_m23
from algorithms.LR_NM.LR_NM_m24 import LR_NM_m24
from algorithms.LR_NM.LR_NM_m25 import LR_NM_m25
from algorithms.LR_NM.LR_NM_m26 import LR_NM_m26
from algorithms.LR_NM.LR_NM_m27 import LR_NM_m27
from algorithms.LR_NM.LR_NM_m28 import LR_NM_m28
from algorithms.LR_NM.LR_NM_m29 import LR_NM_m29
from algorithms.LR_NM.LR_NM_m30 import LR_NM_m30
from algorithms.LR_NM.LR_NM_m31 import LR_NM_m31
from algorithms.LR_NM.LR_NM_m32 import LR_NM_m32
from algorithms.LR_NM.LR_NM_m33 import LR_NM_m33
from algorithms.LR_NM.LR_NM_m34 import LR_NM_m34
from algorithms.LR_NM.LR_NM_m35 import LR_NM_m35
from algorithms.LR_NM.LR_NM_m36 import LR_NM_m36
from algorithms.LR_NM.LR_NM_m37 import LR_NM_m37
from algorithms.LR_NM.LR_NM_m38 import LR_NM_m38
from algorithms.LR_NM.LR_NM_m39 import LR_NM_m39
from algorithms.LR_NM.LR_NM_m40 import LR_NM_m40
from algorithms.LR_NM.LR_NM_m41 import LR_NM_m41
from algorithms.LR_NM.LR_NM_m42 import LR_NM_m42
from algorithms.LR_NM.LR_NM_m43 import LR_NM_m43
from algorithms.LR_NM.LR_NM_m44 import LR_NM_m44
from algorithms.LR_NM.LR_NM_m45 import LR_NM_m45
from algorithms.LR_NM.LR_NM_m46 import LR_NM_m46
from algorithms.LR_NM.LR_NM_m47 import LR_NM_m47
from algorithms.LR_NM.LR_NM_m48 import LR_NM_m48
from algorithms.LR_NM.LR_NM_m49 import LR_NM_m49
from algorithms.LR_NM.LR_NM_m50 import LR_NM_m50
from algorithms.LR_NM.LR_NM_m51 import LR_NM_m51
from algorithms.LR_NM.LR_NM_m52 import LR_NM_m52
from algorithms.LR_NM.LR_NM_m53 import LR_NM_m53
from algorithms.LR_NM.LR_NM_m54 import LR_NM_m54
from algorithms.LR_NM.LR_NM_m55 import LR_NM_m55
from algorithms.LR_NM.LR_NM_m56 import LR_NM_m56
from algorithms.LR_NM.LR_NM_m57 import LR_NM_m57
from algorithms.LR_NM.LR_NM_m58 import LR_NM_m58
from algorithms.LR_NM.LR_NM_m59 import LR_NM_m59
from algorithms.LR_NM.LR_NM_m60 import LR_NM_m60
from algorithms.LR_NM.LR_NM_m61 import LR_NM_m61
from algorithms.LR_NM.LR_NM_m62 import LR_NM_m62
from algorithms.LR_NM.LR_NM_m63 import LR_NM_m63
from algorithms.LR_NM.LR_NM_m64 import LR_NM_m64
from algorithms.LR_NM.LR_NM_m65 import LR_NM_m65
from algorithms.LR_NM.LR_NM_m66 import LR_NM_m66
from algorithms.LR_NM.LR_NM_m67 import LR_NM_m67
from algorithms.LR_NM.LR_NM_m68 import LR_NM_m68
from algorithms.LR_NM.LR_NM_m69 import LR_NM_m69
from algorithms.LR_NM.LR_NM_m70 import LR_NM_m70