from algorithms.LR_NM.LR_NM_gv import LR_NM_gv
from algorithms.LR_NM.LR_NM_m1 import LR_NM_m1
from algorithms.LR_NM.LR_NM_m2 import LR_NM_m2
from algorithms.LR_NM.LR_NM_m3 import LR_NM_m3
from algorithms.LR_NM.LR_NM_m4 import LR_NM_m4
from algorithms.LR_NM.LR_NM_m5 import LR_NM_m5
from algorithms.LR_NM.LR_NM_m6 import LR_NM_m6
from algorithms.LR_NM.LR_NM_m7 import LR_NM_m7
from algorithms.LR_NM.LR_NM_m8 import LR_NM_m8 
from algorithms.LR_NM.LR_NM_m9 import LR_NM_m9
from algorithms.LR_NM.LR_NM_m10 import LR_NM_m10
from algorithms.LR_NM.LR_NM_m11 import LR_NM_m11
from algorithms.LR_NM.LR_NM_m12 import LR_NM_m12
from algorithms.LR_NM.LR_NM_m13 import LR_NM_m13
from algorithms.LR_NM.LR_NM_m14 import LR_NM_m14
from algorithms.LR_NM.LR_NM_m15 import LR_NM_m15
from algorithms.LR_NM.LR_NM_m16 import LR_NM_m16
from algorithms.LR_NM.LR_NM_m17 import LR_NM_m17
from algorithms.LR_NM.LR_NM_m18 import LR_NM_m18
from algorithms.LR_NM.LR_NM_m19 import LR_NM_m19
from algorithms.LR_NM.LR_NM_m20 import LR_NM_m20
from algorithms.LR_NM.LR_NM_m21 import LR_NM_m21
from algorithms.LR_NM.LR_NM_m22 import LR_NM_m22