from algorithms.LR_GA.LR_GA_gv import LR_GA_gv
from algorithms.LR_GA.LR_GA_m1 import LR_GA_m1
from algorithms.LR_GA.LR_GA_m2 import LR_GA_m2
from algorithms.LR_GA.LR_GA_m3 import LR_GA_m3
from algorithms.LR_GA.LR_GA_m4 import LR_GA_m4
from algorithms.LR_GA.LR_GA_m5 import LR_GA_m5
from algorithms.LR_GA.LR_GA_m6 import LR_GA_m6
from algorithms.LR_GA.LR_GA_m7 import LR_GA_m7
from algorithms.LR_GA.LR_GA_m8 import LR_GA_m8
from algorithms.LR_GA.LR_GA_m9 import LR_GA_m9
from algorithms.LR_GA.LR_GA_m10 import LR_GA_m10
from algorithms.LR_GA.LR_GA_m11 import LR_GA_m11
from algorithms.LR_GA.LR_GA_m12 import LR_GA_m12
from algorithms.LR_GA.LR_GA_m13 import LR_GA_m13
from algorithms.LR_GA.LR_GA_m14 import LR_GA_m14
from algorithms.LR_GA.LR_GA_m15 import LR_GA_m15
from algorithms.LR_GA.LR_GA_m16 import LR_GA_m16
from algorithms.LR_GA.LR_GA_m17 import LR_GA_m17
from algorithms.LR_GA.LR_GA_m18 import LR_GA_m18
from algorithms.LR_GA.LR_GA_m19 import LR_GA_m19
from algorithms.LR_GA.LR_GA_m20 import LR_GA_m20
from algorithms.LR_GA.LR_GA_m21 import LR_GA_m21
from algorithms.LR_GA.LR_GA_m22 import LR_GA_m22
from algorithms.LR_GA.LR_GA_m23 import LR_GA_m23
from algorithms.LR_GA.LR_GA_m24 import LR_GA_m24
from algorithms.LR_GA.LR_GA_m25 import LR_GA_m25
from algorithms.LR_GA.LR_GA_m26 import LR_GA_m26
from algorithms.LR_GA.LR_GA_m27 import LR_GA_m27
from algorithms.LR_GA.LR_GA_m28 import LR_GA_m28
from algorithms.LR_GA.LR_GA_m29 import LR_GA_m29
from algorithms.LR_GA.LR_GA_m30 import LR_GA_m30
from algorithms.LR_GA.LR_GA_m31 import LR_GA_m31
from algorithms.LR_GA.LR_GA_m32 import LR_GA_m32
from algorithms.LR_GA.LR_GA_m33 import LR_GA_m33
from algorithms.LR_GA.LR_GA_m34 import LR_GA_m34
from algorithms.LR_GA.LR_GA_m35 import LR_GA_m35
from algorithms.LR_GA.LR_GA_m36 import LR_GA_m36
from algorithms.LR_GA.LR_GA_m37 import LR_GA_m37
from algorithms.LR_GA.LR_GA_m38 import LR_GA_m38